# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171025_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='alias_name',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
